[project]
name = "f1-ml-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.11",
    "dbt-core>=1.11.11",
    "dbt-postgres>=1.10.0",
    "logging>=0.4.9.6",
    "pandas>=3.0.3",
    "psycopg2>=2.9.12",
    "pyarrow>=24.0.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.50",
]
